# Custom Language File for Launcher Customizer

[ejs.app]
title = "MCK Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/injeolmi12/MCKLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/9vrhhVjkC9"

[ejs.settings]
sourceGithubLink = "https://github.com/injeolmi12/MCKLauncher"
supportLink = "https://github.com/injeolmi12/MCKLauncher/issues"

[ejs.welcome]
welcomeHeader = "Minecraft Content Korea"
welcomeDescription = "안녕하세요! 저희는 유튜브, 방송 등 여러분들이 많이 보았던 컨텐츠들을 일반 유저분들과 다 같이 경험하고 재미있게 플레이 해보고 싶은 마음에 만들어진 서버입니다!"
welcomeDescCTA = "HELLO!"
